# Generated by Django 3.0.4 on 2020-04-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('team_size', models.IntegerField()),
                ('working_on', models.CharField(max_length=400)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_skill', models.CharField(max_length=100)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Team_req')),
            ],
        ),
    ]
